[ftplugin]
vim = '''
setlocal noexpandtab
'''

toml = '''
setlocal noexpandtab
'''

php = '''
setlocal softtabstop=4
setlocal shiftwidth=4
setlocal tabstop=4
setlocal expandtab
'''

python = '''
" Indent settings.
setlocal foldmethod=indent
setlocal softtabstop=4
setlocal shiftwidth=4
setlocal textwidth=80
setlocal smarttab
setlocal expandtab
setlocal nosmartindent
'''

html = '''
setlocal includeexpr=substitute(v:fname,'^\\/','','')
setlocal path+=./;/
setlocal softtabstop=2
setlocal shiftwidth=2
setlocal tabstop=2
setlocal expandtab
'''

help = '''
setlocal iskeyword+=:
setlocal iskeyword+=#
setlocal iskeyword+=-
'''

ruby = '''
setlocal iskeyword+=!
setlocal iskeyword+=?
setlocal shiftwidth=2
setlocal softtabstop=2
setlocal tabstop=2
'''
