[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'basyura/TweetVim'
hook_add = '''
let g:tweetvim_tweet_per_page = 200
let g:tweetvim_display_source = 1
let g:tweetvim_display_time = 1
let g:tweetvim_async_post = 1
let g:tweetvim_display_username = 1
let g:tweetvim_buffer_name = '[buffer]'
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
	" let g:EasyMotion_leader_key = '<Space>'
	map <Space> <Plug>(easymotion-prefix)
	" nmap s <Plug>(easymotion-s2)

	" <Leader>f{char} to move to {char}
	map  <Plug>(easymotion-prefix)f <Plug>(easymotion-bd-f)
	nmap <Plug>(easymotion-prefix)f <Plug>(easymotion-overwin-f)

	" s{char}{char} to move to {char}{char}
	nmap s <Plug>(easymotion-overwin-f2)
	vmap s <Plug>(easymotion-bd-f2)

	" Move to line
	map <Plug>(easymotion-prefix)l <Plug>(easymotion-bd-jk)
	nmap <Plug>(easymotion-prefix)l <Plug>(easymotion-overwin-line)

	" Move to word
	map  <Plug>(easymotion-prefix)w <Plug>(easymotion-bd-w)
	nmap <Plug>(easymotion-prefix)w <Plug>(easymotion-overwin-w)
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
vmap <Enter> <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
	let g:user_emmet_leader_key = '<C-S>'
'''

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'tsukkee/unite-tag'

[[plugins]]
repo = 'will133/vim-dirdiff'
hook_add = '''
	let g:DirDiffForceLang = "C"
'''

[[plugins]]
repo = 'fuenor/qfixhowm'

[[plugins]]
repo = 'fuenor/im_control.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# [[plugins]]
# repo = 'shawncplus/phpcomplete.vim'

[[plugins]]
repo = 'nixprime/cpsm'

[[plugins]]
repo = 'kana/vim-tabpagecd'

[[plugins]]
repo = 'thinca/vim-ref'
# on_map = {n = '<Plug>'}
hook_add = '''
	let g:ref_phpmanual_path = expand('~/php-chunked-xhtml')
'''

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
	let g:neoterm_default_mod = 'vertical'
'''

[[plugins]]
repo = 'vim-scripts/dbext.vim'
hook_add = '''
	let g:dbext_default_profile_eyefile = 'type=PGSQL:user=eyefile:dbname=eyefile20170228:host=192.168.0.251'
	let g:dbext_default_profile_oldaqua = 'type=PGSQL:user=dgibex:dbname=aqua20170228:host=192.168.0.251'
	let g:dbext_default_profile_aqua    = 'type=PGSQL:user=laravel:dbname=laravel:host=localhost:port=45002'
'''

[[plugins]]
repo = 'jwalton512/vim-blade'

# [[plugins]]
# repo = 'equalsraf/neovim-gui-shim'

# ==========================================================
# color
# ==========================================================
[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_source = '''
let g:solarized_visibility = "low"
let g:solarized_italic = 0
let g:solarized_underline = 0
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'vim-scripts/newspaper.vim'

[[plugins]]
repo = 'GGalizzi/cake-vim'

[[plugins]]
repo = 'aereal/vim-colors-japanesque'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'hail2u/h2u_colorscheme'

[[plugins]]
repo = 'noahfrederick/vim-hemisu'

[[plugins]]
repo = 'vim-scripts/mayansmoke'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'mhinz/vim-janah'

# [[plugins]]
# repo = 'atelierbram/Base2Tone-vim'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'reedes/vim-colors-pencil'

[[plugins]]
repo = 'nightsense/office'

[[plugins]]
repo = 'nightsense/seagrey'

[[plugins]]
repo = 'archseer/colibri.vim'

[[plugins]]
repo = 'tssm/fairyfloss.vim'

[[plugins]]
repo = 'rakr/vim-one'
